build:
    environment:
        php:
            version: 7.0.8
imports:
    - php
tools:
    external_code_coverage: true
    php_cpd: false
    php_sim: false
filter:
    excluded_paths:
        - docs/*
        - tests/*
        - vendor/*
