build:
  environment:
    php:
      version: 7.1
imports:
  - php
tools:
  external_code_coverage:
    timeout: 1800
    runs: 3
  php_cpd: false
  php_sim: false
filter:
  excluded_paths:
    - docs/*
    - tests/*
    - vendor/*
